# Generated by Django 2.2.12 on 2026-05-25 15:40

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libAPI', '0001_initial'),
        ('publishAPI', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StateSave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=400, null=True)),
                ('save_time', models.DateTimeField(auto_now=True, db_index=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('save_id', models.UUIDField(default=uuid.uuid4)),
                ('data_dump', models.TextField()),
                ('shared', models.BooleanField(default=False)),
                ('base64_image', models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/files', location='/code/file_storage'), upload_to='circuit_images')),
                ('version', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('is_arduino', models.BooleanField(default=False)),
                ('is_submission', models.BooleanField(blank=True, null=True)),
                ('esim_libraries', models.ManyToManyField(to='libAPI.Library')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publishAPI.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('save_id', models.CharField(max_length=500, unique=True)),
                ('data_dump', models.TextField()),
                ('name', models.CharField(default='Untitled', max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('media', models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/files', location='/code/file_storage'), upload_to='circuit_images_esim')),
                ('shared', models.BooleanField(default=True)),
                ('save_time', models.DateTimeField(auto_now=True)),
                ('is_arduino', models.BooleanField(default=False)),
                ('esim_libraries', models.ManyToManyField(to='libAPI.Library')),
            ],
        ),
        migrations.CreateModel(
            name='ArduinoModelSimulationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(default=True, null=True)),
                ('save_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saveAPI.StateSave')),
            ],
        ),
    ]
