# Generated by Django 2.2.12 on 2026-06-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statesave',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
