# Generated by Django 2.2.12 on 2026-05-25 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflowAPI', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ACAnalysisParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(default='dec', max_length=200)),
                ('stop', models.CharField(max_length=200, null=True)),
                ('start', models.CharField(max_length=200, null=True)),
                ('pointsBydecade', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CircuitTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DCSweepParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=200, null=True)),
                ('sweepType', models.CharField(default='Linear', max_length=200)),
                ('start', models.CharField(max_length=200, null=True)),
                ('stop', models.CharField(max_length=200, null=True)),
                ('step', models.CharField(max_length=200, null=True)),
                ('parameter2', models.CharField(max_length=200, null=True)),
                ('start2', models.CharField(max_length=200, null=True)),
                ('stop2', models.CharField(max_length=200, null=True)),
                ('step2', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('text', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('is_arduino', models.BooleanField(default=False)),
                ('is_reported', models.BooleanField(default=False, null=True)),
                ('active_branch', models.CharField(max_length=20, null=True)),
                ('active_version', models.CharField(max_length=20, null=True)),
                ('ac_analysis', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='publishAPI.ACAnalysisParameters')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dc_sweep', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='publishAPI.DCSweepParameters')),
                ('fields', models.ManyToManyField(to='publishAPI.Field')),
                ('state', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflowAPI.State')),
            ],
        ),
        migrations.CreateModel(
            name='TFAnalysisParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outputNodes', models.BooleanField(default=False)),
                ('outputVoltageSource', models.CharField(max_length=200, null=True)),
                ('inputVoltageSource', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransientAnalysisParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=200, null=True)),
                ('stop', models.CharField(max_length=200, null=True)),
                ('step', models.CharField(max_length=200, null=True)),
                ('skipInitial', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransitionHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transition_time', models.DateTimeField(auto_now_add=True)),
                ('reviewer_notes', models.CharField(blank=True, max_length=500)),
                ('is_done_by_reviewer', models.BooleanField(default=False, null=True)),
                ('project', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='publishAPI.Project')),
                ('transition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflowAPI.Transition')),
                ('transition_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transition Histories',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_open', models.BooleanField(default=True)),
                ('report_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=500)),
                ('approved', models.BooleanField(default=None, null=True)),
                ('project', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='publishAPI.Project')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to=settings.AUTH_USER_MODEL)),
                ('resolver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tf_analysis',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='publishAPI.TFAnalysisParameters'),
        ),
        migrations.AddField(
            model_name='project',
            name='transient_analysis',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='publishAPI.TransientAnalysisParameters'),
        ),
    ]
