# Generated by Django 2.2.12 on 2026-05-25 15:41

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saveAPI', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeLimit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='runtimeStat',
            fields=[
                ('exec_time', models.IntegerField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_time', models.DateTimeField(auto_now=True, db_index=True)),
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='spiceFile',
            fields=[
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/code/file_storage'), upload_to='')),
                ('upload_time', models.DateTimeField(auto_now=True, db_index=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='simulationAPI.Task')),
            ],
        ),
        migrations.CreateModel(
            name='simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_type', models.CharField(blank=True, max_length=30, null=True)),
                ('simulation_time', models.DateTimeField(auto_now_add=True)),
                ('netlist', models.TextField()),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('schematic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saveAPI.StateSave')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulationAPI.Task')),
            ],
        ),
    ]
