# Generated by Django 2.2.12 on 2026-05-25 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('public', models.BooleanField(default=False)),
                ('report', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('restricted_for_creator', models.BooleanField(default=True, verbose_name='Transition allowed for all users of specified roles except creator')),
                ('only_for_creator', models.BooleanField(default=False, verbose_name='Transition that ONLY the creator should be able to do it.')),
                ('event_creator', models.CharField(blank=True, max_length=200, null=True, verbose_name='Event Text for the Creator')),
                ('history_creator', models.CharField(blank=True, max_length=200, null=True, verbose_name='History Text for the Creator')),
                ('event_reviewer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Event Text for the Reviewer')),
                ('history_reviewer', models.CharField(blank=True, max_length=200, null=True, verbose_name='History Text for the Reviewer')),
                ('event_other', models.CharField(blank=True, max_length=200, null=True, verbose_name='Event Text for the Other User')),
                ('history_other', models.CharField(blank=True, max_length=200, null=True, verbose_name='History Text for the Other User')),
                ('from_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fromtransitions', to='workflowAPI.State')),
                ('role', models.ManyToManyField(related_name='role', to='auth.Group')),
                ('to_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='totransitions', to='workflowAPI.State')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('del_own_states', models.ManyToManyField(blank=True, related_name='del_own_states', to='workflowAPI.State', verbose_name='Can Delete own Project')),
                ('edit_own_states', models.ManyToManyField(blank=True, related_name='edit_own_states', to='workflowAPI.State', verbose_name='Can Edit Details and Status own Project')),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permission_role', to='auth.Group')),
                ('view_other_states', models.ManyToManyField(blank=True, related_name='view_other_states', to='workflowAPI.State', verbose_name='Can View other Project')),
                ('view_own_states', models.ManyToManyField(blank=True, related_name='view_own_states', to='workflowAPI.State', verbose_name='Can View own Project')),
            ],
        ),
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_arduino', models.BooleanField(default=False)),
                ('is_type_reviewer', models.BooleanField(default=False)),
                ('is_type_staff', models.BooleanField(default=False)),
                ('is_default_role', models.BooleanField(default=False)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
    ]
