# Generated by Django 2.2.12 on 2026-05-25 15:41

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saveAPI', '0001_initial'),
        ('simulationAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArduinLTIConsumer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('consumer_key', models.CharField(max_length=50)),
                ('secret_key', models.CharField(max_length=50)),
                ('score', models.FloatField(blank=True, null=True)),
                ('con_weightage', models.FloatField(default=60)),
                ('scored', models.BooleanField()),
                ('view_code', models.BooleanField()),
                ('initial_schematic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arduino_initial_schematic', to='saveAPI.StateSave')),
                ('model_schematic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arduino_model_schematic', to='saveAPI.StateSave')),
                ('test_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saveAPI.ArduinoModelSimulationData')),
            ],
        ),
        migrations.CreateModel(
            name='ArduinoLTISession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200, null=True)),
                ('lis_result_sourcedid', models.CharField(max_length=300, null=True)),
                ('lis_outcome_service_url', models.CharField(max_length=300, null=True)),
                ('oauth_nonce', models.CharField(max_length=300)),
                ('oauth_timestamp', models.CharField(max_length=300)),
                ('oauth_consumer_key', models.CharField(max_length=300)),
                ('oauth_signature_method', models.CharField(max_length=300)),
                ('oauth_version', models.CharField(max_length=300)),
                ('oauth_signature', models.CharField(max_length=300)),
                ('lti_consumer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ltiAPI.ArduinLTIConsumer')),
                ('simulations', models.ManyToManyField(to='saveAPI.ArduinoModelSimulationData')),
            ],
        ),
        migrations.CreateModel(
            name='ArduinoLTISimData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('circuit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saveAPI.StateSave')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltiAPI.ArduinoLTISession')),
            ],
        ),
        migrations.CreateModel(
            name='lticonsumer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('consumer_key', models.CharField(max_length=50)),
                ('secret_key', models.CharField(max_length=50)),
                ('score', models.FloatField(blank=True, null=True)),
                ('sim_params', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None)),
                ('scored', models.BooleanField()),
                ('initial_schematic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initial_schematic', to='saveAPI.StateSave')),
                ('model_schematic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_schematic', to='saveAPI.StateSave')),
                ('test_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulationAPI.simulation')),
            ],
        ),
        migrations.CreateModel(
            name='ltiSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200, null=True)),
                ('lis_result_sourcedid', models.CharField(max_length=300, null=True)),
                ('lis_outcome_service_url', models.CharField(max_length=300, null=True)),
                ('oauth_nonce', models.CharField(max_length=300)),
                ('oauth_timestamp', models.CharField(max_length=300)),
                ('oauth_consumer_key', models.CharField(max_length=300)),
                ('oauth_signature_method', models.CharField(max_length=300)),
                ('oauth_version', models.CharField(max_length=300)),
                ('oauth_signature', models.CharField(max_length=300)),
                ('lti_consumer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ltiAPI.lticonsumer')),
                ('simulations', models.ManyToManyField(to='simulationAPI.simulation')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('lms_success', models.BooleanField(null=True)),
                ('ltisession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ltiAPI.ltiSession')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltiAPI.lticonsumer')),
                ('schematic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saveAPI.StateSave')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student_simulation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulationAPI.simulation')),
            ],
        ),
        migrations.CreateModel(
            name='ArduinoSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('lms_success', models.BooleanField(null=True)),
                ('ltisession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ltiAPI.ArduinoLTISession')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltiAPI.ArduinLTIConsumer')),
                ('schematic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saveAPI.StateSave')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student_simulation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ltiAPI.ArduinoLTISimData')),
            ],
        ),
    ]
