# Generated by Django 2.2.12 on 2026-07-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltiAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arduinosubmission',
            name='passback_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arduinosubmission',
            name='passback_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='submission',
            name='passback_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='passback_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
