# Generated by Django 2.2.12 on 2026-07-16 10:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltiAPI', '0002_add_passback_status_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='comparison_result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
