# Generated by Django 2.2.12 on 2026-07-17 11:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ltiAPI', '0003_add_submission_analytics_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='lticonsumer',
            name='rubric_weights',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='rubric_breakdown',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
