# Generated by Django 2.2.12 on 2026-05-25 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(max_length=200)),
                ('saved_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LibrarySet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=False)),
                ('name', models.CharField(default='default', max_length=24)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LibraryComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('svg_path', models.CharField(max_length=400)),
                ('thumbnail_path', models.CharField(max_length=400)),
                ('description', models.CharField(max_length=400)),
                ('data_link', models.URLField()),
                ('full_name', models.CharField(max_length=200)),
                ('keyword', models.CharField(max_length=200)),
                ('symbol_prefix', models.CharField(max_length=10)),
                ('component_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library', to='libAPI.Library')),
            ],
        ),
        migrations.AddField(
            model_name='library',
            name='library_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libAPI.LibrarySet', verbose_name='library_set'),
        ),
        migrations.CreateModel(
            name='FavouriteComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change', models.DateTimeField(auto_now=True)),
                ('component', models.ManyToManyField(to='libAPI.LibraryComponent')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComponentAlternate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=1)),
                ('dmg', models.PositiveSmallIntegerField()),
                ('full_name', models.CharField(max_length=200)),
                ('svg_path', models.CharField(max_length=400)),
                ('parent_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternate_component', to='libAPI.LibraryComponent')),
            ],
        ),
    ]
